version: '2'
services:
  maps-lb:
    scale: 1
    start_on_create: true
  geoserver:
    scale: 1
    start_on_create: true
  web:
    scale: 1
    start_on_create: true
  datadir:
    scale: 1
    start_on_create: true
  mapproxy:
    scale: 1
    start_on_create: true
  ngnix:
    scale: 1
    start_on_create: true
  bstync:
    scale: 1
    start_on_create: true
  mapserver:
    scale: 1
    start_on_create: true

